project:
  type: website
website:
  title: WDI
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/vincentarelbundock/WDI
        aria-label: WDI GitHub
      - text: Home
        file: index.qmd
      - text: News
        file: NEWS.md
      - text: Citation
        file: CITATION.md
      - text: Functions
        menu:
          - text: WDI
            file: man/WDI.qmd
          - text: WDIsearch
            file: man/WDIsearch.qmd
          - text: WDIbulk
            file: man/WDIbulk.qmd
          - text: WDIcache
            file: man/WDIcache.qmd
          - text: WDI_data
            file: man/WDI_data.qmd
